
package com.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://Employee.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printName", targetNamespace = "http://Employee.com/", className = "com.employee.PrintName")
    @ResponseWrapper(localName = "printNameResponse", targetNamespace = "http://Employee.com/", className = "com.employee.PrintNameResponse")
    @Action(input = "http://Employee.com/EmployeeService/printNameRequest", output = "http://Employee.com/EmployeeService/printNameResponse")
    public String printName(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
